server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: task-management-system

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yml
      enabled: true

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true

    config:
      import: optional:file:.env[.properties]

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days