version: "3.9"

volumes:
  postgres-data:
    driver: local

services:
  task-management-system:
    build: ../
    container_name: task-management-system
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: 'postgres:17-alpine'
    container_name: postgresql
    ports:
      - ${POSTGRES_PORT_MAPPING}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped